### ISSUE TITLE
没见到论坛，就把问题反馈到这吧

### ISSUE THREAD

**Issue by tim-hub** [ionhammer/voidAR#1]
## 图像训练，无评星

平台是64bit Win7, 32bit Unity3d 5.2.2。
## 容易崩溃
- 拖进ui prefab点play就蹦
- 不放UI, 很久后，会出现play mode

**Comment by ionhammer** [comment]
请问VoidAR是哪个版本？

**Comment by tim-hub** [comment]
应该是13天前的版本，应该是0.03
